### ISSUE TITLE
waypoint_control with take off node

### ISSUE THREAD

**Issue by levenberg** [raaslab/mavros_offboard_control#1]
In UAVWaypointControl.cpp, the flight mode set and arming set were commented. So I use` rosrun  uav_control uav_take_off` node to arming the drone, after that `roslaunch uav_control waypoint_control.launch` to start the waypoint mission. However, the uav_take_off node was shutdown 

> Reason given for shutdown:[new node registered with same name].

So what is the problem?
Thanks,
Huai

**Comment by kevinlyu1** [comment]
That means that you are trying to run the node twice. You should run both of them again and look at the `rosnode list` to see if the node is still running. If it is still running than it's fine and ros just shut down the node because there is a duplicate.

**Comment by levenberg** [comment]
Thanks. I changed one of the node name thus both of them could run at the same time.  So why did you comment the flight mode set and arming set in the waypoint mission and  motion primitives mission?

**Comment by kevinlyu1** [comment]
It didn't fit our needs, that's why we took it out of the code.
